### PR TITLE
release: 1.7.0

### PR DESCRIPTION
**Pull request by davidhewitt**
I think it's time to push out various collected bugfixes and tidy ups, along with the new `pyproject.toml` support.

I'll put live on Tuesday unless I hear a reason to delay.

### CODE REVIEW

**Comment by davidhewitt** [comment]
Will wait for #352 as it has a fix for an edge case with `DIST_EXTRA_CONFG`.

**Comment by alex** [comment]
Hmm, I see the tag was pushed, but this wasn't merged and it's not on PyPI. Was the tag intentional?

**Comment by davidhewitt** [comment]
The deploy is busted, I'm going to rip out the tag one more time and then re-push. (Speedbumps from switching to `pyproject.toml` for setuptools-rust's own packaging!)

**Comment by davidhewitt** [comment]
Ok, release is pushed to PyPI. CI failure is spurious network error, I'm going to merge this. Sorry if anyone got spam from the recreation of the setuptools-rust Github release.

**Pull request merged**
