### PR TITLE
Fix compilation bug in toolchain >= 1.70.0

### LINKED ISSUE #320: Compilation in setuptools_rust fails with `1.70.0-nightly` toolchain
# Assumptions

- problematic toolchain
-- `rustc 1.70.0-nightly (db0cbc48d 2023-03-26)`
-- `rustc 1.70.0-nightly (478cbb42b 2023-03-28)`
- toolchain not affected
-- `rustc 1.68.0-stable`

# Description

`wheel` package generation fails with latest toolchain, when `crate-type = ["cdylib"]` is not contained in `Cargo.toml`.

# Cause

The following command in build process will not work:

```
cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features 'python pyo3/extension-module' --no-default-features -- --crate-type cdylib
```

Instead, following works:

```
cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features 'python pyo3/extension-module' --no-default-features --crate-type cdylib
```

# Workaround

any of the following avoids the bug:

- Write `crate-type = ["cdylib"]` in `Cargo.toml`
- Write `args=["--crate-type", "cdylib"]` in initializer of `RustExtension`

Sample:

```py
                RustExtension(
                    'namespace.package', 'Cargo.toml',
                    binding = Binding.PyO3,
                    args = ["--crate-type", "cdylib"],
                )
```

I will create PRs later.

### PR DESCRIPTION
**Pull request by yasuo-ozu**
Fix #320

Please see the discussion in https://github.com/PyO3/setuptools-rust/pull/321

### CODE REVIEW

**Comment by yasuo-ozu** [comment]
I think the mypy error is occured out of my code, but I don't know why it fails while the `main` branch is passed.

**Comment by davidhewitt** [comment]
Are you sure this is an intentional change? I don't see it mentioned in https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md

**Comment by yasuo-ozu** [comment]
Actually I cannot figure out which change on rustc break the compatibility.
(it occurs between ff4b772 ... 8a73f50)

Recently --crate-type option is implemented in cargo, so I think it is safer to use --crate-type option on cargo.

**Comment by yasuo-ozu** [comment]
@davidhewitt I think the mypy error is not related on this PR, so is it good for you to fix it in the same branch?

**Comment by davidhewitt** [comment]
Yes, I can fix the mypy error separately.

Argument for using cargo options seems reasonable to me. It looks like `--crate-type` was added in cargo 1.64, so can you please rework this PR to use the new options for 1.64 or later?

We can then document this in the CHANGELOG as "changed" rather than "fixed".

**Comment by yasuo-ozu** [comment]
Thanks a lot. I fixed the version and modified CHANGELOG.
Could you please release it after it is merged?

**Review by davidhewitt — APPROVED** [review]
Thanks - I'll try to tidy things up on `main` with a view to releasing tomorrow.

**Pull request merged**
