### PR TITLE
Use Github Actions instead of Travis

### PR DESCRIPTION
**Pull request by davidhewitt**
This is a follow-up to #77 which adds testing (by migrating to github actions).

This isn't ready to merge; on the way I found that I had to build a custom pyo3 branch to fix PyPy support.

I also had to fixup a few pieces of the setuptools-rust examples to behave better cross-platform!

### CODE REVIEW

**Comment by alex** [comment]
Seems to be failing as expected, if you point the `Cargo.toml` at https://github.com/PyO3/pyo3/pull/1179 hopefully they'll pass 😬

**Comment by davidhewitt** [comment]
Agreed; it's pretty late here so I'm going to finish this tomorrow. Ideally in the morning but could be later in the day...

**Comment by davidhewitt** [comment]
As https://github.com/PyO3/pyo3/pull/1179 is now merged, I'm testing this PR against the pyo3 master. Hopefully green!

**Comment by davidhewitt** [comment]
I think I missed one of the toml files, so have pointed that one also at master and re-pushed.

**Comment by davidhewitt** [comment]
CI passed 🎉 . So this is blocked until PyO3 0.12.1 releases.

**Comment by alex** [comment]
😅 good to know that PR works in any event.

**Comment by davidhewitt** [comment]
PyO3 0.12 released and working nicely here!

**Pull request merged**
