### PR TITLE
Fix RustBin setuptools install

### PR DESCRIPTION
**Pull request by jameshilliard**
Fixes: #274

### CODE REVIEW

**Review by messense — COMMENTED** [review]
Thanks, I think we should add a test case to ensure that it does not regress in the future, right now we only test with wheel.

https://github.com/PyO3/setuptools-rust/blob/main/examples/hello-world/noxfile.py

**Comment by jameshilliard** [comment]
> Thanks, I think we should add a test case to ensure that it does not regress in the future, right now we only test with wheel.

Yeah, think I got the setuptools only install working in a test, along with an install exclusion filter so that setuptools doesn't also install scripts in places that don't make sense like:
```
venv/lib/python3.10/site-packages/maturin-0.13.0-py3.10-linux-x86_64.egg/maturin-0.13.0.data/scripts/maturin
```

**Review by messense — APPROVED** [review]
Thanks, looks great!

**Comment by davidhewitt** [comment]
👍 thanks!

**Pull request merged**
