### PR TITLE
github workflows for html-py-ever

### PR DESCRIPTION
**Pull request by 0kalekale**
as per issue #51 , added a example travis ci config which builds uploads wheels for pythons 3.6-3.8 and uploads a source distribution to pypi.

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks! Personally I prefer github actions these days, I wonder if you've tried that? I can help write an example for that if you're interested.

**Comment by 0kalekale** [comment]
yeah i too prefer github action, infact just a while ago i used it to build and test my own python-rust module.

https://www.github.com/0kalekale/ipaddr/tree/master/.github%2Fworkflows%2Ftest-module.yml

the issue happen to mention travis so, what do you say?

**Comment by davidhewitt** [comment]
👍 awesome! I think if we provide a github actions example, that's probably better in my opinion so we could close the issue with that?

**Comment by 0kalekale** [comment]
sure

**Comment by 0kalekale** [comment]
@davidhewitt with this you can close the issue

**Comment by davidhewitt** [comment]
👍 thank you so much for this!

**Pull request merged**
